### ISSUE TITLE
syntax error, unexpected 'version' (T_STRING) (View: /var/www/html/vendor/aw-studio/fjord/resources/views/partials/logo.blade.php)

### ISSUE THREAD

**Issue by lucaspdude** [aw-studio/fjord#10]
I get this error when trying to access /admin route on the browser.

`syntax error, unexpected 'version' (T_STRING) (View: /var/www/html/vendor/aw-studio/fjord/resources/views/partials/logo.blade.php)`

I'm using laravel on Docker and i when i try to use artisan route:list i recieve the following error:

`Call to a member function getConfig() on null  at vendor/aw-studio/fjord/src/Crud/Controllers/Concerns/HasConfig.php:40
`

**Comment by cbl** [comment]
I released the fix, thanks for letting me know about the bug.
