### ISSUE TITLE
Command "fjord:admin" is not defined. 

### ISSUE THREAD

**Issue by ryanchanplc** [aw-studio/fjord#11]
Followed the guide to get Fjord installed, but running `php artisan fjord:admin` got an error.

```
Command "fjord:admin" is not defined.
Did you mean one of these?
      fjord:guard
      fjord:install
```

Thanks

**Comment by ryanchanplc** [comment]
sorry my bad, the fjord:install is not successful. 
After fixing to install fjord successfully , `php artisan fjord:admin` works now.

**Comment by cbl** [comment]
Great, let me know if when you have any troubles.
