### ISSUE TITLE
"cols" is not a supported method for the Vue component "fj-info". Supported methods: title, text, width, heading, class, prop, slot, bind.

### ISSUE THREAD

**Issue by awesomentw** [aw-studio/fjord#14]
Hi,
i run into an issue . This is new installation,  running using artisan serve.

http://localhost:8000/admin/profile/settings

![image](https://user-images.githubusercontent.com/58770051/83895271-c0154e00-a752-11ea-93ea-9006b84230ba.png)

**Comment by cbl** [comment]
The cols method is deprecated, replace it with `width`. Seem like i forgot to update it in the ProfileSettingsConfig.

**Comment by awesomentw** [comment]
Wow. You are quick. changing cols to width fixed issue.
