### ISSUE TITLE
Issue with validation

### ISSUE THREAD

**Issue by awesomentw** [aw-studio/fjord#17]
I think its error. 

```
  $form->input('name')
            ->title(trans('app.name'))
            ->width(12)
            ->rules('required')
            ->max(255);

  $form->input('code')
            ->title(trans('app.code'))
            ->width(12)
            ->rules('required')
            ->max(255);
```

When im creating all works as expected fields are required.
When im updating even if both fields are filled they are still required. 

Here is screencars - https://nimb.ws/oCkAVa

ps. Man, this is some nice pice of work.

**Comment by cbl** [comment]
`required` is checking whether a post parameter exists. Fjord is only sending fields that have been changed in your form when updating. 
I guess you want that your field cannot be empty. I would recomment to apply a creationRule `required` and a global rule `min:1` like so:

```php
  $form->input('name')
            ->title(trans('app.name'))
            ->width(12)
            ->rules('min:1')
            ->creationRules('required')
            ->max(255);

  $form->input('code')
            ->title(trans('app.code'))
            ->width(12)
            ->rules('min:1')
            ->creationRules('required')
            ->max(255);
```

**Comment by awesomentw** [comment]
Works like a charm.
