### ISSUE TITLE
Fresh install home form should have translatable option

### ISSUE THREAD

**Issue by xsindesign** [aw-studio/fjord#19]
I just installed the package and it looks great ! Can't wait to play with it ! 👍

One small thing tho, on a fresh install we have a "home" example and a language switcher which don't work by default because the form don't have the translatable option.
I figured it out quickly but it's confusing for a first impression, I would suggest either don't activate 2 languages by default or apply the option.

**Comment by cbl** [comment]
That is a good idea, we want to show that translatable apps can be created. I am going to make the HomeConfig fields translatable by default. 😉
