### ISSUE TITLE
Discord link on home page dead

### ISSUE THREAD

**Issue by chrispage1** [aw-studio/fjord#22]
Hi! I've just been having a look at Fjord after trying out Twill, another open source Laravel CMS. However, it's looking a little inactive and Fjord looks so slick, nice work!

Just in case you didn't know the Discord link on the sites home page seems to be dead, do you still have a Discord running?

Thanks!

**Comment by cbl** [comment]
Thanks for letting me know, i guess i only created a 24 hour link. 🤦
The new one should be permanent.
https://discord.gg/u4qpb5P
