### ISSUE TITLE
Navigation Preset issue

### ISSUE THREAD

**Issue by oguzoztas** [aw-studio/fjord#26]
Hello, recently i get default preset error from freshly installed app.
error link is : https://flareapp.io/share/x7KV0JPR

This error occur after 2.3v

"No navigation entry preset with name "user.user" found."
Thanks.

**Comment by cbl** [comment]
Hi, does the file `./fjord/app/Config/User/UserConfig.php` exist?

**Comment by oguzoztas** [comment]
Yes it exist. Also when i remove every preset in navigationconfig pages works. When i type php artisan fjord:nav, just permissions and profile presets shown.

**Comment by cbl** [comment]
It looks like your crud routes are not loading. This may be due to route caching.
Does `php artisan route:clear` solve the issue?

**Comment by oguzoztas** [comment]
No. I cache nothing and fresh install no other packages etc. Using laravel 7.15 But i working on windows local env. with laragon. probably some windows thing happening.

**Comment by cbl** [comment]
Okay, the issue is propably in here: https://github.com/aw-studio/fjord/blob/master/src/Crud/RouteServiceProvider.php

I cannot reproduce it at the moment. I will try to do it next week.

**Comment by oguzoztas** [comment]
Hello I found a solution smt like that #27 . 
Its working now. Thanks anyway for this crazy cms

**Comment by cbl** [comment]
Happy to hear you like Fjord! I pushed a modified fix, hope it works for you know. Thank you for the solution.
