### ISSUE TITLE
Content-Length mismatch, received 31417 bytes out of the expected 999096 http://repo.packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

### ISSUE THREAD

**Issue by sanmitpawar** [aw-studio/fjord#33]
Hello,
 
I have a fresh laravel 7 project installed on my system when I am trying to install Fjord using following command I am getting an error (please refer image) in the composer.

**Installation command: composer require aw-studio/fjord**

![image](https://user-images.githubusercontent.com/19944808/85282094-c1f84480-b4a8-11ea-8dde-f8c62f558ebf.png)

**Comment by cbl** [comment]
This seems to be an issue with composer.
https://stackoverflow.com/questions/38635257/composer-content-length-mismatch
