### ISSUE TITLE
pick time in datetimepicker 

### ISSUE THREAD

**Issue by febuc** [aw-studio/fjord#34]
First of all, thank you for fjord. It is really a great tool. While configuring it I came across an issue.
When trying to pick a date there is no possibility to also pick an according time.<br>
![datetimepicker](https://user-images.githubusercontent.com/54474460/85383645-7f824680-b540-11ea-89d5-ab97c7a5f890.png)<br>
It is also impossible to write a time manually.

**Comment by cbl** [comment]
Hey, just add `->onlyDate(false)` to your field configuration.

**Comment by febuc** [comment]
Thank you very much for your quick response. This works great for me.
