### ISSUE TITLE
Repository [belongs-to-many] not found.

### ISSUE THREAD

**Issue by laravelbap** [aw-studio/fjord#43]
Hi,

i have some issue with relation field. When i try to connect related (categories) to current record ( project) . I got error on ajax response "Repository [belongs-to-many] not found."

it's not working on 2.4.* but works fine on 2.3.*

Something is changed in the configuration, and I should add something?

here is my field config

```
     $form->relation('categories')
                ->title(__f('app.categories'))
                ->preview(function ($table) {

                    $table->col('title');
                });
```

**Comment by cbl** [comment]
That is actually a Bug in Fjord. I am going to fix that asap. You can downgrade to 2.3 Till I releases the fix

**Comment by cbl** [comment]
I released a fix and a [test](https://github.com/aw-studio/fjord/blob/ad87bc839bd3b1f420067135ea6f15088ac4c345/tests/php/CrudRepositories/BelongsToManyRepositoryTest.php) for the belongsToMany relation.
