### ISSUE TITLE
imgPath method not static

### ISSUE THREAD

**Issue by gavinmarc** [aw-studio/fjord#45]
Hi, we're currently testing out Fjord and we really like it. 

All of our media is stored in Google storage. The upload works fine. 
Unfortunately the media is not being displayed in Fjord because of this static image path: 
```
imgPath(image) {
    return `/storage/${image.id}/${image.file_name}`;
},
```

Is it possible to use the medias getUrl() method?

**Comment by cbl** [comment]
Hey, that is indeed not a very flexible solution to displaying images. It is not possible at the moment. I will change it to use the url from the medias getUrl method.

**Comment by cbl** [comment]
@gavinmarc This commit should solve the issue: https://github.com/aw-studio/fjord/commit/0046e0122db18bd09f9ac25aa56569835ba18ff0
