### ISSUE TITLE
Error on Composer Require!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [aw-studio/fjord#6]
I see this error when trying to required the package on a fresh laravel installation.
Error in BaseForm.php
**Laravel**: v7.11

![err](https://user-images.githubusercontent.com/5323832/82317086-08501480-99ce-11ea-9ab1-0cba78e23187.PNG)

**Comment by cbl** [comment]
It could be that `composer dump-autoload` solves the problem.

Which php version do you have installed?

**Comment by Mu9tafa-Online** [comment]
I tried dump-autoload but it is still the same, I'm on PHP 7.3

**Comment by joke2k** [comment]
@Mu9tafa-Online Fjord requires PHP 7.4+
