### ISSUE TITLE
Installation request for symfony/process (locked at v5.0.7) -> satisfiable by symfony/process[v5.0.7].

### ISSUE THREAD

**Issue by LarryEitel** [aw-studio/fjord#9]
Unable to install. Running latest Laravel and PHP.

**Comment by cbl** [comment]
It seems to me like that a dependency requires a different version of symfony/process than the one you have installed. 

You can try to fix it by removing your **vendor** folder and the **composer.lock** file. Then add `"aw-studio/fjord": "^2.2"` to require in your composer json and run `composer install`.

If this doesn't work, post the full log so I can see more about whats going on.

**Comment by cbl** [comment]
Could you post the full log? @Krato
